commit_template: |
  style: reformat by ${restyler.name}

restylers:
  - isort:
      enabled: false
  - reorder-python-imports:
      enabled: false
  - autopep8:
      enabled: false
  - yapf:
      enabled: false
  - astyle:
      enabled: false
  - clang-format:
      enabled: false
  - prettier-markdown:
      arguments: ["--prose-wrap", "preserve"]
  - "*"
